# Generated by Django 5.0.6 on 2024-06-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_section_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
