# Generated by Django 5.0.6 on 2024-06-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_module_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="video",
            field=models.FileField(default="", upload_to="videos/"),
            preserve_default=False,
        ),
    ]
