# Generated by Django 5.0.6 on 2024-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_module_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="is_preview",
            field=models.BooleanField(default=False),
        ),
    ]
