# Generated by Django 5.0.6 on 2024-06-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_payment_pidx"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="section",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.DeleteModel(
            name="Module",
        ),
    ]
