# Generated by Django 5.0.6 on 2024-06-21 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_discussion_reply_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="discussion",
            unique_together={("user", "section", "message")},
        ),
    ]
