# Generated by Django 5.0.6 on 2024-06-21 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_course_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("title", "instructor")},
        ),
    ]
