# Generated by Django 5.0.6 on 2024-06-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_course_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="thumbnail_images/default.png",
                null=True,
                upload_to="thumbnail_images/",
            ),
        ),
    ]
