# Generated by Django 5.0.6 on 2024-06-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
