# Generated by Django 5.0.6 on 2024-07-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_course_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
    ]
